name: ShellCheck

on:
  push:
    branches: [ master ]
    paths:
      - '**.sh'
      - 'res'
  pull_request:
    branches: [ master ]
    paths:
      - '**.sh'
      - 'res'

jobs:
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run ShellCheck
      uses: ludeeus/action-shellcheck@master
      with:
        scandir: './'
        format: gcc
